import styles from '../styles/app.module.css'
import Head from 'next/head'
import Header from './header'
import Sidebar from './sidebar'
import MobileSidebar from './mobile_sidebar'
import { ReactNode, useState } from 'react'
import { useSession } from 'next-auth/react'


export default function Layout({ children } : {children : ReactNode}) {
    const [side, setSide] = useState(false)

    const { data: session, status } = useSession()

    

    const mail:string = session ? session.user?.name! : ""
    

  return (
    <>
        <Head>
            <title>Savelink</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header} >
            <Header side={side} setSide = {setSide} name = {mail} />
        </header>

        {side && <MobileSidebar side={side} setSide={setSide} />}
        <main className={styles.main} >
            <div className={styles.side}>
                <Sidebar/>
            </div>
            <div className={styles.pages}>
                <main>{children}</main>
            </div>
        </main>
    </>
  )
}