import styles from '../styles/app.module.css'
import Head from 'next/head'
import Header from './header'
import Sidebar from './sidebar'
import MobileSidebar from './mobile_sidebar'
import { ReactNode, useState } from 'react'

interface Props {
    children: ReactNode
}

export default function Layout({ children } : Props) {
    const [side, setSide] = useState(false)

  return (
    <>
        <Head>
            <title>Savelink</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header} >
            <Header side={side} setSide = {setSide} />
        </header>

        {side && <MobileSidebar side={side} setSide={setSide} />}
        <main className={styles.main} >
            <div className={styles.side}>
                <Sidebar/>
            </div>
            <div className={styles.pages}>
                <main>{children}</main>
            </div>
        </main>
    </>
  )
}