import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import List from '../components/lists'
import styles from '../styles/dashboard.module.css'
import { useRef } from 'react'

const Dashboard: NextPage = () => {


    const homeRef = useRef(null)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <header  className={styles.header}>
        <div className={styles.hamburger}>
            <Image
            src='/menu-fill.svg'
            alt='menu'
            width={30}
            height={30}
            />
        </div>

        <div className={styles.searchbar}>
            <input type="text" placeholder='Search through links' />
        </div>
       
    </header>

    

    <main className = {styles.main}>
        <section className={styles.sidebar} >
            <ul>
                <li  ref={homeRef}>
                    <Image 
                        src='/links.svg' 
                        alt='links'
                        width={25}
                        height={25}
                    /> 
                    <span>All links </span>
                </li>
                <li>
                    <Image 
                        src='/bookmark.svg' 
                        alt='links'
                        width={25}
                        height={25}
                    /> 
                    <span >Starred</span>
                </li>
                <li>
                    <Image 
                        src='/lightbulb.svg' 
                        alt='links'
                        width={25}
                        height={25}
                    />   
                    <span>Categories</span>
                </li>
            </ul>
        </section>


        <section>
            <List/>               
        </section>  
    </main>

    <footer className={styles.footer}>
        <div className={styles.add} >
            <button>
                <Image 
                    src='/add-circle.svg'
                    alt='add'
                    width={60}
                    height={60}
                />
            </button>
        </div>
    </footer>
    </div>
  )
}

export default Dashboard;

