import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to save-links</h1>

        <p>Save and categorise your important links from all across the internet in one place.</p>

        <div>
          <Link href="/dashboard">
            <button> Sign in with google </button>
          </Link>
          {/* <button> Sign in with twitter</button> */}
          <Link href='/demo/dashboard'>  
            <button> Demo sign in </button>
          </Link> 

        </div>
      </main>
    </div>
  )
}

export default Home
