import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { signIn, useSession} from 'next-auth/react'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const {data : session, status} = useSession();
  const loading = status === 'loading'

  console.log("status ", status)

  const handleSignIn = (e: { preventDefault: () => void }) => {
    e.preventDefault();
    signIn("google")
  }
  const router = useRouter()
  let name = session?.user?.email

  useEffect(() => {
    if(session) {console.log(session?.user?.email, session?.user?.image)}
    
    if(session) {router.push(`/v1/${name}/`)}
  }, [session])
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to save-links</h1>

        <p>Save and categorise your important links from all across the internet in one place.</p>

        <div>
            <a href={`/api/auth/signin`}
             onClick={handleSignIn}>
              <button> Sign in with google </button>
            </a>
          {/* <button> Sign in with twitter</button> */}
          <Link href='/demo/dashboard'>  
            <button> Demo sign in </button>
          </Link> 

        </div>
      </main>
    </div>
  )
}

export default Home
